#!/usr/bin/env bash

set -e

COUNTRY="US"   # change this to whatever country code you want

if protonvpn connect "$COUNTRY" >/dev/null 2>&1; then
    notify-send "Proton VPN connected to $COUNTRY."
else
    notify-send "Proton VPN failed to connect to $COUNTRY."
fi
