#!/usr/bin/env bash

set -e

# This is used for the Hang at the end, for disabling it.
SCRIPT_PATH=$(readlink -f "${BASH_SOURCE[0]}")

# Ensure $HOME exists
if [ -z "$HOME" ]; then
    echo "HOME variable not set!"
    exit 1
fi

# Ask install scope
read -r -p "Install as 'root' or 'user'? [Default = user]: " INSTALL_LOCATION

# Set install directory and sudo usage
if [ "$INSTALL_LOCATION" = "root" ]; then
    ICONS_DIR="/usr/share/icons/Proton AG"
    SUDO_CMD="sudo"
    echo "Installing in $ICONS_DIR"
else
    ICONS_DIR="$HOME/.local/share/icons/Proton AG"
    SUDO_CMD=""
    echo "Installing in $ICONS_DIR"
fi

# Make icons folder
echo
echo "Making icons directory '$ICONS_DIR'"
$SUDO_CMD mkdir -p "$ICONS_DIR" || echo "Failed to create directory $ICONS_DIR!"
echo "Icons directory '$ICONS_DIR' made."
echo

# Grab Proton SVG files
echo "Downloading Proton icons..."

for file_url in \
    "proton.svg=https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fp-purple_mio6jr.svg" \
    "vpn.svg=https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fvpn_f9embt.svg" \
    "mail.svg=https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fmail_xxy4bg.svg" \
    "calendar.svg=https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fcalendar_ylg2jq.svg" \
    "drive.svg=https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fdrive_wo2nx4.svg" \
    "docs.svg=https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fproton-docs-icon_q9p090.svg" \
    "pass.svg=https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fpass_wl1fk9.svg" \
    "lumo.svg=https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Flumo_k0nljk.svg" \
    "sheets.svg=https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fproton-sheets-icon.svg" \
    "auth.svg=https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fauthenticator.svg"
do
    filename="${file_url%%=*}"
    url="${file_url#*=}"
    $SUDO_CMD wget -qO "$ICONS_DIR/$filename" "$url" &
done

wait

echo "All Proton icons downloaded."

# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging (local only): " response
    if [ "$response" = "disable" ]; then
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$SCRIPT_PATH"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        echo
        for i in {5..1}; do
            echo -n "Exiting in $i..."
            sleep 1
            echo -ne "\r"
        done
        echo "Exiting now.        "
    fi
fi
