#!/usr/bin/env bash

set -e

# This is used for the Hang at the end, for disabling it.
SCRIPT_PATH=$(readlink -f "${BASH_SOURCE[0]}")

# Check if script is run as su.
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root because icons folder is root." >&2
    echo "The script runs 'sudo mkdir -p /usr/share/icons/Proton/'" >&2
    exit 1
fi

# Ensure $HOME exists
if [ -z "$HOME" ]; then
    echo "HOME variable not set!"
    exit 1
fi

# Check if Proton VPN CLI is installed.
if ! command -v protonvpn >/dev/null 2>&1; then
    echo "Proton VPN CLI is not installed." >&2
    echo "Why are you even running this..." >&2
    exit 1
fi

# Definitions
ICONS_DIR="/usr/share/icons/Proton AG"
REPO_DIR="$HOME/GitHub/NikoboiNFTB/Proton-VPN"
DESKTOP_FILE_REPO="$REPO_DIR/protonvpn.desktop"
DESKTOP_DIR="$HOME/Desktop"
DESKTOP_FILE_DESKTOP="$DESKTOP/protonvpn.desktop"
REAL_HOME="$HOME"

echo

# Make icons folder
echo "Making icons directory..."
mkdir -p $ICONS_DIR || echo "Failed to create directory!"
echo "Icons directory made."

echo

# Grab Proton SVG files
echo "Downloading Proton icons..."
wget -qO $ICONS_DIR/vpn.svg "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fvpn_f9embt.svg"
wget -qO $ICONS_DIR/mail.svg "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fmail_xxy4bg.svg"
wget -qO $ICONS_DIR/calendar.svg "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fcalendar_ylg2jq.svg"
wget -qO $ICONS_DIR/drive.svg "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fdrive_wo2nx4.svg"
wget -qO $ICONS_DIR/docs.svg "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fproton-docs-icon_q9p090.svg"
wget -qO $ICONS_DIR/pass.svg "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fpass_wl1fk9.svg"
wget -qO $ICONS_DIR/lumo.svg "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Flumo_k0nljk.svg"
echo "All Proton icons downloaded."

echo

echo "Getting .desktop file"





# Replace $HOME with your actual home
sed -i "s|Icon=\$HOME|Icon=$REAL_HOME|g" "$DESKTOP_FILE_REPO"
sed -i "s|Exec=\$HOME|Exec=$REAL_HOME|g" "$DESKTOP_FILE_REPO"







# Replace your actual home with $HOME
sed -i "s|Icon=$REAL_HOME|Icon=\$HOME|g" "$DESKTOP_FILE"
sed -i "s|Exec=$REAL_HOME|Exec=\$HOME|g" "$DESKTOP_FILE"






# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging (local only): " response
    if [ "$response" = "disable" ]; then
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$SCRIPT_PATH"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        echo
        for i in {5..1}; do
            echo -n "Exiting in $i..."
            sleep 1
            echo -ne "\r"
        done
        echo "Exiting now.        "
    fi
fi
