#!/usr/bin/env bash

set -e

# This is used for the Hang at the end, for disabling it.
SCRIPT_PATH=$(readlink -f "${BASH_SOURCE[0]}")

# Ensure $HOME exists
if [ -z "$HOME" ]; then
    echo "❌ HOME variable not set!"
    exit 1
fi

# COMMENTED FOR TESTING PURPOSES
# Check if Proton VPN CLI is installed.
# if ! command -v protonvpn >/dev/null 2>&1; then
    # echo "Proton VPN CLI is not installed." >&2
    # exit 1
# fi

# Definitions
USER_NAME=NikoboiNFTB
REPO_NAME=Proton-VPN
REPO_DIR="$HOME/GitHub/$USER_NAME/$REPO_NAME"
DESKTOP_DIR="$HOME/Desktop"

# Clone repo, update if already present.
if [ -d "$REPO_DIR/.git" ]; then
    echo "ℹ️  Updating repository..."
    cd "$REPO_DIR"
    git pull
else
    echo "ℹ️  Cloning repository..."
    git clone https://github.com/NikoboiNFTB/Proton-VPN "$REPO_DIR"
fi

# Replace $HOME with your actual home
sed -i "s|Icon=\$HOME|Icon=$HOME|g" "$REPO_DIR/vpn.desktop"
sed -i "s|Exec=\$HOME|Exec=$HOME|g" "$REPO_DIR/vpn.desktop"

# Copy .desktop files
echo "ℹ️  Copying desktop file..."

mkdir -p "$DESKTOP_DIR"
cp "$REPO_DIR/vpn.desktop" "$DESKTOP_DIR/vpn.desktop"

# Change your actual home back to $HOME in repo
sed -i "s|Icon=$HOME|Icon=\$HOME|g" "$REPO_DIR/vpn.desktop"
sed -i "s|Exec=$HOME|Exec=\$HOME|g" "$REPO_DIR/vpn.desktop"

# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging (local only): " response
    if [ "$response" = "disable" ]; then
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$SCRIPT_PATH"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        echo
        for i in {5..1}; do
            echo -n "Exiting in $i..."
            sleep 1
            echo -ne "\r"
        done
        echo "Exiting now.        "
    fi
fi
