#!/usr/bin/env bash

set -e

# This is used for the Hang at the end, for disabling it.
SCRIPT_PATH=$(readlink -f "${BASH_SOURCE[0]}")

# Ensure $HOME exists
if [ -z "$HOME" ]; then
    echo "HOME variable not set!"
    exit 1
fi

# Definitions
REPO_DIR="$HOME/GitHub/NikoboiNFTB/Proton-VPN"
DESKTOP="$HOME/Desktop"
DESKTOP_ICON="$DESKTOP/proton-vpn-connect.desktop"
APPLICATIONS_ICON="/usr/share/applications/proton-vpn-connect.desktop"

# Ask install scope
read -r -p "Install as root or user? [user]: " INSTALL_LOCATION

# Set install directory
if [ "$INSTALL_LOCATION" = "root" ]; then
    ICONS_DIR="/usr/share/icons/Proton AG"
    echo "Installing in $ICONS_DIR"
else
    ICONS_DIR="$HOME/.local/share/icons/Proton AG"
    echo "Installing in $ICONS_DIR"
fi

# Make icons folder
echo "Making icons directory $ICONS_DIR"
sudo mkdir -p "$ICONS_DIR/" || echo "Failed to create directory!"
echo "Icons directory $ICONS_DIR made."

# Grab Proton SVG files
echo "Downloading Proton icons..."
sudo wget -qO "$ICONS_DIR/proton.svg" "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fp-purple_mio6jr.svg"
sudo wget -qO "$ICONS_DIR/vpn.svg" "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fvpn_f9embt.svg"
sudo wget -qO "$ICONS_DIR/mail.svg" "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fmail_xxy4bg.svg"
sudo wget -qO "$ICONS_DIR/calendar.svg" "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fcalendar_ylg2jq.svg"
sudo wget -qO "$ICONS_DIR/drive.svg" "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fdrive_wo2nx4.svg"
sudo wget -qO "$ICONS_DIR/docs.svg" "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fproton-docs-icon_q9p090.svg"
sudo wget -qO "$ICONS_DIR/pass.svg" "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fpass_wl1fk9.svg"
sudo wget -qO "$ICONS_DIR/lumo.svg" "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Flumo_k0nljk.svg"
sudo wget -qO "$ICONS_DIR/sheets.svg" "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fproton-sheets-icon.svg"
sudo wget -qO "$ICONS_DIR/auth.svg" "https://pmecdn.protonweb.com/image-transformation/?s=c&image=image%2Fupload%2Fstatic%2Flogos%2Ficons%2Fauthenticator.svg"
echo "All Proton icons downloaded."

# Check if Proton VPN CLI is installed.
# if ! command -v protonvpn >/dev/null 2>&1; then
    # echo "Proton VPN CLI is not installed." >&2
    # echo "Why are you even running this..." >&2
    # exit 1
# fi





# Replace $HOME with your actual home
# sed -i "s|Icon=\$HOME|Icon=$HOME|g" "$REPO_DIR/proton-vpn-connect.desktop"
# sed -i "s|Exec=\$HOME|Exec=$HOME|g" "$REPO_DIR/proton-vpn-connect.desktop"

# Copy .desktop files
# echo "Getting .desktop file"

# Replace your actual home with $HOME
# sed -i "s|Icon=$HOME|Icon=\$HOME|g" "$REPO_DIR/proton-vpn-connect.desktop"
# sed -i "s|Exec=$HOME|Exec=\$HOME|g" "$REPO_DIR/proton-vpn-connect.desktop"





# Hang

KEEP_OPEN=true

if [ "$KEEP_OPEN" = true ]; then
    echo
    read -p "Press 'Enter' to exit / Type 'disable' to disable hanging (local only): " response
    if [ "$response" = "disable" ]; then
        sed -i 's/^KEEP_OPEN=true/KEEP_OPEN=false/' "$SCRIPT_PATH"
        echo
        echo "KEEP_OPEN set to false"
        echo "Change 'KEEP_OPEN=true' to enable"
        echo
        for i in {5..1}; do
            echo -n "Exiting in $i..."
            sleep 1
            echo -ne "\r"
        done
        echo "Exiting now.        "
    fi
fi
